---
- hosts: localhost
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes  # Ensure apt cache is up to date

    - name: Install Java (required for Elasticsearch)
      apt:
        name: openjdk-11-jdk
        state: present  # Install the necessary JDK for Elasticsearch

    - name: Add Elasticsearch GPG key
      apt_key:
        url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        state: present  # Add the GPG key for Elasticsearch repository

    - name: Add Elasticsearch repository
      apt_repository:
        repo: "deb https://artifacts.elastic.co/packages/7.x/apt stable main"
        state: present  # Add the official Elasticsearch repository

    - name: Install Elasticsearch
      apt:
        name: elasticsearch
        state: present  # Install Elasticsearch from the repository

    - name: Enable and start Elasticsearch service
      systemd:
        name: elasticsearch
        enabled: yes  # Ensure Elasticsearch service starts on boot
        state: started  # Start the Elasticsearch service immediately

    - name: Set up cron job to move logs older than 30 days to S3
      cron:
        name: "Move Elasticsearch data to S3"
        minute: "0"
        hour: "0"
        job: "/usr/local/bin/phase_data.sh"  # Cron job runs daily to move old data to S3

    - name: Create script to phase data older than 30 days to S3
      copy:
        dest: /usr/local/bin/phase_data.sh
        mode: 0755
        content: |
          #!/bin/bash
          find /var/lib/elasticsearch/ -type f -mtime +30 -exec aws s3 cp {} s3://es-data-bucket/ \;  # Move data older than 30 days to S3
